Article 3events and criteria
aimclub/rostok pull request #126
Opened 2023-10-05 09:35 UTC by MikhailChaikovskii

2023-10-06 09:13 UTC, Huowl requested changes

2023-10-06 09:13 UTC, Huowl commented on rostok/virtual_experiment/sensors.py
> +            output[idx] = np.nan_to_num(output[idx], nan=9999).tolist()
Это конечно мое гениальное решение. Может, стоит как-то по другому избавляться от `nan`?

2023-10-06 09:42 UTC, MikhailChaikovskii commented on rostok/criterion/simulation_flags.py
> +            flat_idx_ = list(robot_contacts.keys())[0]
Сейчас нет, но нам явно нужна какая-то индексация нормальная, я бы даже сказал система лейблов, возможно с несколькими уровнями.

2023-10-06 09:44 UTC, MikhailChaikovskii commented on rostok/criterion/simulation_flags.py
> +        if not (self.time_last_contact is None):
У меня пару раз были какие-то траблы с if None, поэтому я стараюсь избегать этого и прописываю явно, но вообще ты прав.

2023-10-06 09:46 UTC, MikhailChaikovskii commented on rostok/virtual_experiment/sensors.py
> +            output[idx] = np.nan_to_num(output[idx], nan=9999).tolist()
Стоит вообще изменить сенсоры, сделать их единообразными, сделать проверку на форму данных и прочее. Весь этот мердж это просто набор мелких фиксов, чтобы мы могли уже сказать, что мастер работает и пойти дальше.

2023-10-07 15:03 UTC, MikhailChaikovskii commented on rostok/criterion/simulation_flags.py
> +        for position in trajectory_points.values():
Я не понял вопрос, так там и нет проверки на nan. Вообще говоря, position в nan не должен обращаться, если он обратился это уже ошибки и это должно ловиться на уровне сенсора.

2023-10-09 11:53 UTC, Huowl commented
Временные исправления с дальнейшим изменением работы сенсоров

2023-10-16 11:10 UTC, Huowl approved these changes

2023-10-16 11:10 UTC, merged