Refactoring control optimize class
aimclub/rostok pull request #130
Opened 2023-10-26 21:34 UTC by ZharkovKirill

Поменял архитектуру со странным наследованием. Добавил базовый класс `BasePrepareOptiVar`, который создает функцию вознаграждения. Переместил в него все методы, которые связанны с размерностями вектора, что позволило сделать более универсальный оптимизатор. Добавил варианты оптимизации через брут форс и директ. Добавил пример использования `control_optimizer_test`.

2023-10-27 11:21 UTC, Huowl requested changes

2023-10-27 11:21 UTC, Huowl commented on rostok/trajectory_optimizer/control_optimizer.py
> +            result_group_object[scen_name].append((results[1], results[0]))
А веса сценарием где-то рассчитается? Я не нашел где.

2023-10-30 13:00 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +            result_group_object[scen_name].append((results[1], results[0]))
✔️

2023-10-30 13:00 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +                print("TIMEOUT")
✔️

2023-10-30 13:00 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +                 variants: list,
✔️

2023-10-30 13:00 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +        print('x:', x)
✔️

2023-10-30 13:00 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +        is_vis = self.is_vis_decision(graph) and self.is_vis
✔️

2023-10-30 13:01 UTC, ZharkovKirill commented on rostok/trajectory_optimizer/control_optimizer.py
> +def build_equal_starting_positions(graph: GraphGrammar, starting_finger_angles):
✔️

2023-10-30 13:08 UTC, Huowl approved these changes

2023-10-30 13:09 UTC, merged