Запуск MCTS на конфигах
aimclub/rostok pull request #132
Opened 2023-11-02 14:07 UTC by ZharkovKirill

Добавил несколько раздельных конфигов под Реворд, Симуляцию, Оптимизацию управления, Гиперпарметры. В новом разделе `pipeline`
Пример использования в app

2023-11-03 09:43 UTC, Huowl requested changes
Доделай комментарии, или возвращаемые типы опиши в функциях. Мне что-то тяжко было смотреть логику. Немного ощущается спагетти код.

2023-11-03 09:44 UTC, Huowl commented
Может поможет
![2023-11-03-11-03-50](https://github.com/aimclub/rostok/assets/49783047/a50c3760-b427-4c25-a05a-d6b6467f1dfa)

2023-11-15 19:00 UTC, ZharkovKirill commented on app/tendon_driven_cfg.py
> +def get_random_force_with_null_grav(amp):
Это файлик про общий пайплайн под tendon.

2023-11-15 19:00 UTC, ZharkovKirill commented on app/tendon_driven_cfg.py
> +HARD_OBJECT_SET = [
Ну тоже самое, что и ниже

2023-11-15 19:20 UTC, ZharkovKirill commented on app/mcts_runner.py
> +        mcts_manager.run_search(mcts_hyper.base_iteration, 1, 1, 2)
Добавил

2023-11-15 19:21 UTC, ZharkovKirill commented on rostok/pipeline/generate_grasper_cfgs.py
> +def add_grasp_events_from_cfg(sim: GraspScenario, cfg: GraspObjective):
Преназвал

2023-11-22 13:27 UTC, Huowl commented on rostok/pipeline/generate_grasper_cfgs.py
> +                            optimisation_control_cgf: GlobalOptimisationRewardCfg |
И я не помню

2023-11-22 13:28 UTC, Huowl approved these changes

2023-11-22 13:28 UTC, merged